spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: userR
        password: userR
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    application:
        name: forumEngine
server:
  port: 8976
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict
        secure: true
springdoc:
  api-docs:
    path: /api-docs
